pipeline {
    agent any
    environment {
        DJANGO_SETTINGS_MODULE = "app.settings"
        PYTHON_VENV = 'venv'
        GIT_SSH_KEY = credentials('jenkins-ssh-agent-private-key')
    }
    stages{
        stage('Checkout') {
            steps {
            script {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-ssh-agent-private-key', keyFileVariable: 'SSH_KEY')]) {
                    sh 'mkdir -p ~/.ssh'
                    sh 'echo "$SSH_KEY" > ~/.ssh/id_rsa'
                    sh 'chmod 600 ~/.ssh/id_rsa'
                    sh 'ssh-keyscan -H github.com >> ~/.ssh/known_hosts'  
                    sh 'git clone git@github.com:amakarudze/to-do.git'  
                
            }
            }
        }
        }
        stage('Set up Python Environment'){
            steps {
                script {
                    sh 'python3 -m venv $PYTHON_VENV'
                    sh '. $PYTHON_VENV/bin/activate'
                }
            }
        }
        stage('Install dependencies') {
            steps {
                script {
                    sh '. $PYTHON_VENV/bin/activate && pip install -r requirements.txt'
                }
            }
        }
        stage('Run Migrations') {
            steps {
                script {
                    sh '. $PYTHON_VENV/bin/activate && python manage.py migrate'
                }
            }
        }
        stage('Run Test') {
            steps {
                script {
                    sh '. $PYTHON_VENV/bin/activate pytest'
                }
            }
        }
    }
 }