pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'apt install python3.11-venv'
                sh 'python3 -m venv /opt/.venv && source /opt/.venv/bin/activate'
                sh 'cd to-do'
                sh 'py.test --junit-xml test-reports/results.xml'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }

        }

    }
}