name: Run Tests
on: [push, pull_request]
jobs:
  Set-up-Django-Project:
    runs-on : ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.12", "3.13"]
        poetry-version: ["2.1.1"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help

      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: |
          cd to-do
          poetry install
      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@v2.3.0
      - name: Start XVFB
        run: |
          Xvfb :99 &
      - name: Run Migrations
        run: |
          cd to-do
          poetry run python manage.py migrate
      - name: Run the automated tests (for example)
        run: | 
          cd to-do
          poetry run pytest --cov-branch --cov-report=xml
    
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: amakarudze/to-do
